[build-system]
requires = ["setuptools>=61.0", "et-xmlfile>=1.1.0", "openpyxl>=3.0", "plotly>=5.1", "tenacity>=6.2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ontoviz-bio"
version = "1.3.1"
authors = [
  { name="Matthias Ley", email="matthias.ley@pm.me" },
]
description = "Drug- and phenotype-ontology visualization GUI"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Mnikley/OntoViz"
"Bug Tracker" = "https://github.com/Mnikley/OntoViz/issues"
