[build-system]
requires = ["setuptools>=61.0", "et-xmlfile>=1.1.0", "openpyxl>=3.0", "plotly>=5.1", "tenacity>=6.2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ontoloviz"
version = "1.3.3"
authors = [
  { name="Matthias Ley", email="matthias.ley@pm.me" },
]
description = "OntoloViz drug- and phenotype-ontology visualization GUI"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Mnikley/OntoloViz"
"Bug Tracker" = "https://github.com/Mnikley/OntoloViz/issues"
"Releases" = "https://github.com/Mnikley/OntoloViz/releases"

[tool.black]
line-length = 88
target-version = ['py310']
