name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      id: pylint_analysis
      run: |
        echo "PYLINT_SCORE=$(pylint $(git ls-files '*.py') --max-line-length=127 --disable=C,import-error --exit-zero --output-format=text | sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p')" >> $GITHUB_ENV
    - name: echo test
      run: |
        echo $PYLINT_SCORE
        echo ${{ steps.pylint_analysis.PYLINT_SCORE }}
        echo ${{ env.PYLINT_SCORE }}
    - name: Create Pylint Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 303283c4b9026d59cda9e9dd9f697110
        filename: pylint_badge.json
        label: Pylint score
        message: ${{ env.PYLINT_SCORE }}
        color: green
